import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/app/(contents)/HeaderPage/pages";
import {AllProductProvider} from "@/context/AllProductContext";
import {ModalProvider} from "@/context/AddEditModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${inter.className} min-h-screen grid grid-cols-1`}>
      <AllProductProvider>
        <ModalProvider>
          <header className={`flex min-w-screen h-fit`}>
            <HeaderPage/>
          </header>
          <main className="flex flex-col items-center min-w-screen p-2 sm:p-0 overflow-hidden">
            <div className={`flex flex-col min-h-full justify-center overflow-hidden`}>
              <div className={`text-4xl text-center uppercase text-blue-400 mt-2`}>Products</div>
              <div className={`grid grid-cols-1 gap-2 overflow-y-auto p-2`}>
                {children}
              </div>
            </div>
          </main>
        </ModalProvider>
      </AllProductProvider>
      </body>
      </html>
  );
}
